spring:
  application:
    name: gateway-server
    
  cloud:
    refresh:
      enabled: true
    config:
      uri:
      - http://localhost:8888
      
#management:#  endpoint:#    gateway:#      enabled: true
#    web:
#      exposure:
#        include:
#        - "*"  
        
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"  